name: UI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          override: true

      - name: Show initial farm UI
        run: cargo test initial_farm_ui -- --nocapture
